# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562679505321806b19c025eb8a6b886494be9743b76518cbcc4cf38189c4cf15f2df1b585ce80860741b3161451c966c450e862469aeeede32b058ac1ef36c92

test:
  secret_key_base: 127e5780f06347820e770caa5f4050fc5aac6feea50de363691baa050b273edafd56d5edea293ab46abaf624685fcdd3d7063e167e13015b11801ae723a72537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
